### ISSUE TITLE
coco_karpathy_train.json is broken

### ISSUE THREAD

**Issue by ChrisLiu6** [RotsteinNoam/FuseCap#4]
Hi! The coco_karpathy_train.json file seems to end up unexpectedly.  The following is at the end of the file:

{"caption": "A clock on a lamp post stands beside a white building with a wood balcony, surrounded by a green bush and a dark shadow.", "image": "train2014/COCO_train2014_000000024019.jpg", "image_id": "coco_24019"}, {"caption": "Two men, one wearing a white shirt and blue jeans, walk down a street lined with metal and concrete fences. A brick pill

**Comment by RotsteinNoam** [comment]
Hi, thank you for bringing this to our attention. The issue with the file has been fixed.
