### ISSUE TITLE
Experimental settings of image-text retrieval in Table 3

### ISSUE THREAD

**Issue by byougert** [RotsteinNoam/FuseCap#5]
Hi,
thanks for your great work and wonderful project.

When reading the paper, I have a question about the experimental settings of image-text retrieval in Table 3, where BLIP<sub>FuseCap</sub> outperforms the original BLIP by a large margin.

As marked in the paper, when performing the image-text retrieval on BLIP<sub>FuseCap</sub>, the texts in **testing set** are also enriched.
Is it somewhat unreasonable to enrich the test texts? After all, the paired visual information is required when enriching the text.

**Comment by RotsteinNoam** [comment]
Hi @byougert and thank you for your kind words!
You are correct in noting that enrichment during testing requires paired visual information. However, it's important to consider that the initial creation of captions (for both training and testing data) also involves the use of paired visual information - human annotators view the images to generate the captions. We automated a process that enhances these original captions, resulting in a more detailed version of them.

We believe that the improved retrieval performance not only confirms the success of enriching the captions but also shows that vision-language models can benefit from and successfully use these additional details as a discriminative factor.

We hope this addresses your concern. We appreciate your interest in our work and welcome any more questions you might have!

**Comment by byougert** [comment]
Hi, @RotsteinNoam and thanks for your patient reply.

When performing the task of image captioning, it is undoubted that the proposed FuseCap exhibits the excellent ability of fine-grained attention; while in Table 3 which mainly reflects the **retrieval performance**, I am concerned that it may be inappropriate to change the **test caption** into an enriched version, which indeed requires the corresponding visual information.
Unfortunately, before the retrieval, the correspondence relation is, in principle, agnostic. 

If directly using the enriched test caption to perform retrieval evaluation,  this evaluation actually utilize the correspondence relation and it seems somewhat illogical.

Anyhow, thanks for your reply again.
