### ISSUE TITLE
CLIPScore calculation

### ISSUE THREAD

**Issue by Fa-ti-ma** [RotsteinNoam/FuseCap#7]
Hello,
Thank you for your interesting work. I have a question regarding the calculation of the CLIPScore of the enriched captions. Since CLIP can only support around 70 tokens, how did you pass the long enriched caption to generate the score?

**Comment by RotsteinNoam** [comment]
When our enriched captions exceeded the CLIP text encoder's maximum token limit of 77, the tokenizer ended up truncating the end of the captions. This likely wasn't the best outcome for the fusecap captions, as it meant we weren't able to fully measure all the additional extracted information. Despite this, we opted to continue using the standard model and evaluation protocol.
