### ISSUE TITLE
training and inference costs for fuser

### ISSUE THREAD

**Issue by YoojLee** [RotsteinNoam/FuseCap#8]
Hi, thanks for such an interesting work.

Could you please provide training and inference costs for fine-tuning FuseCap? (GPU specs and training / inference time)

Thanks!

**Comment by RotsteinNoam** [comment]
Hi and thank you for the kind words!

Unfortunately, we did not keep track of the exact times.
From what we recall, the training took about two days on one A100 GPU, and the inference took about a week on 8 A100 GPUs.

**Comment by YoojLee** [comment]
well was it 40GB or 80GB? Thx!

**Comment by RotsteinNoam** [comment]
40GB 🙂

**Comment by YoojLee** [comment]
Thanks for your replies! :) helped me a lot.
